# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OfficeHoursDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OfficeHoursDemo
	
	pod 'BeagleScaffold'
	pod 'YogaKit', :git => 'https://github.com/ZupIT/YogaKit'

  target 'OfficeHoursDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OfficeHoursDemoUITests' do
    # Pods for testing
  end

end
